In [1]:
import numpy as np
w=0.5
b=0.2
x=np.random.randn(10000,1)
sigx=1/(1+np.exp(-(w*x+b)))
y=np.zeros(sigx.shape)
y[sigx>0.5]=1

In [2]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver='lbfgs')
lr.fit(x,y)
lr.score(x,y)

C:\Users\hxs10\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9995

In [3]:
lr.predict(x[:2])

array([0., 0.])

In [5]:
lr.coef_

array([[17.83510137]])

In [7]:
lr.intercept_

array([7.10147824])

In [8]:
y[:2]

array([[0.],
       [0.]])

In [10]:
def logreg_test(x,y,alpha,nmax):
    X = np.append(np.ones((x.shape[0],1)),x,axis=1)
    m, n = X.shape
    w = np.zeros((n,1))
    for i in range(nmax):
        J = np.sum(y*np.logaddexp(0, -np.dot(X,w)) + (1-y)*np.logaddexp(0, np.dot(X,w)))
        dw = np.dot(X.T, -y+(1+np.exp(-np.dot(X,w)))**-1)
        w -= alpha * dw
        if np.remainder(i,np.floor(nmax/4))==0:
            print((i,w,J))
    return w
    
#     X=np.append(np.ones((x.shape[0],1)),x,axis=1)
#     m,n=X.shape
#     w=np.zeros((n,1))
#     #print((0,w))
#     for i in range(nmax):
#         A=1/(1+np.exp(-np.dot(X,w)))
#         J=np.sum(-(y*np.log(A)+(1-y)*np.log(1-A)))
#         dZ=A-y
#         dw=np.dot(X.T,dZ)/m
#         w-=alpha*dw
#         if np.remainder(i,np.floor(nmax/4))==0:
#             print((i,w,J))
#     return w

In [11]:
def test_logreg_perf(x,y,alpha,nmax):
    w_est=logreg_test(x,y,alpha,nmax)
    sigx_hat=1/(1+np.exp(-(w_est[0]+w_est[1]*x)))
    y_hat=np.zeros(sigx_hat.shape)
    y_hat[sigx_hat>0.5]=1
    erate=np.absolute(y_hat-y).sum()/x.shape[0]
    print('Error Rate is '+str(erate/100)+'%')

In [12]:
test_logreg_perf(x,y,0.001,10000)

(0, array([[1.583     ],
       [3.72841867]]), 6931.471805599453)
(2500, array([[13.25108184],
       [33.32818655]]), 182.78005653263577)
(5000, array([[16.73825359],
       [42.04196559]]), 146.9147474249545)
(7500, array([[19.19432435],
       [48.17382224]]), 129.35479167137362)
Error Rate is 4e-06%


In [13]:
test_logreg_perf(x,y,0.003,40000)

(0, array([[ 4.749   ],
       [11.185256]]), 6931.471805599453)
(10000, array([[30.75543207],
       [77.02494888]]), 83.61732256670706)
(20000, array([[38.97990088],
       [97.55550766]]), 67.04044658079874)
(30000, array([[ 44.8250507 ],
       [112.15033427]]), 58.75445131219432)
Error Rate is 2e-06%


In [14]:
w_est = logreg_test(x,y,0.002,10000)

(0, array([[3.166     ],
       [7.45683734]]), 6931.471805599453)
(2500, array([[16.7691656 ],
       [42.11916158]]), 146.67162474173534)
(5000, array([[21.17491809],
       [53.11695111]]), 118.10411663245074)
(7500, array([[24.28451845],
       [60.87664417]]), 104.04325948071208)


In [15]:
w_est

array([[26.77084109],
       [67.0809313 ]])

In [17]:
[lr.coef_, lr.intercept_]

[array([[17.83510137]]), array([7.10147824])]

In [18]:
y[:5]

array([[0.],
       [0.],
       [1.],
       [1.],
       [0.]])

In [19]:
lr.predict(x[:5])

array([0., 0., 1., 1., 0.])

In [20]:
1/(1+np.exp(-w_est[0]-w_est[1]*x[:5]))

array([[6.12304662e-16],
       [1.81508501e-34],
       [1.00000000e+00],
       [1.00000000e+00],
       [5.60892218e-05]])

In [23]:
def logreg_l2reg(x,y,alpha,beta,nmax):
    X = np.append(np.ones((x.shape[0],1)),x,axis=1)
    m, n = X.shape
    w = np.zeros((n,1))
    for i in range(nmax):
        J = np.sum(y*np.logaddexp(0, -np.dot(X,w)) + (1-y)*np.logaddexp(0, np.dot(X,w))) + 0.5*np.dot(w.T,w)
        dw = np.dot(X.T, -y+(1+np.exp(-np.dot(X,w)))**-1)/m + beta*w
        w -= alpha * dw
        if np.remainder(i,np.floor(nmax/4))==0:
            print((i,w,J))
    return w

In [24]:
w_l2 = logreg_l2reg(x,y,0.002,0.001,10000)

(0, array([[0.0003166 ],
       [0.00074568]]), array([[6931.4718056]]))
(2500, array([[0.48175734],
       [1.14664596]]), array([[3600.1098123]]))
(5000, array([[0.71969842],
       [1.73461146]]), array([[2772.57197406]]))
(7500, array([[0.8819886 ],
       [2.14518736]]), array([[2371.64957557]]))


In [25]:
1/(1+np.exp(-w_l2[0]-w_l2[1]*x[:5]))

array([[0.22017458],
       [0.05555664],
       [0.84862982],
       [0.99337485],
       [0.41662655]])

In [26]:
w_l2

array([[1.00751702],
       [2.46632168]])

In [27]:
w_l2 = logreg_l2reg(x,y,0.003,0.002,20000)

(0, array([[0.0004749 ],
       [0.00111853]]), array([[6931.4718056]]))
(5000, array([[0.87624615],
       [2.13095131]]), array([[2383.88375332]]))
(10000, array([[1.18427054],
       [2.9219679 ]]), array([[1847.57724089]]))
(15000, array([[1.38365859],
       [3.43589543]]), array([[1607.07992265]]))


In [28]:
w_l2

array([[1.53180798],
       [3.8170887 ]])

In [29]:
1/(1+np.exp(-w_l2[0]-w_l2[1]*x[:5]))

array([[0.12080921],
       [0.01198076],
       [0.93342521],
       [0.99955932],
       [0.36620802]])

In [30]:
y[:5]

array([[0.],
       [0.],
       [1.],
       [1.],
       [0.]])

In [31]:
lr.predict(x[:5])

array([0., 0., 1., 1., 0.])

In [32]:
1/(1+np.exp(-w_l2[0]-w_l2[1]*x[:5])) > 0.5

array([[False],
       [False],
       [ True],
       [ True],
       [False]])